apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-podmonitor
spec:
  replicas: 3
  selector:
    matchLabels:
      podmonitorapp: example-app
  template:
    metadata:
      labels:
        podmonitorapp: example-app
    spec:
      containers:
      - name: example-app
        image: quay.io/brancz/prometheus-example-app:v0.5.0
        ports:
        - name: web
          containerPort: 8080
